apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
    - name: nginx
      image: nginx

#---

#apiVersion: v1
#kind: pod
#metadata:
#  name: demo
#spec:
#  containers:
#    - name: nginx
#      image: nginx