apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-containers
spec:
  containers:
    - name: sample
      image: docker.io/rkalluru/ephmeral-practice

# debug from another pod
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
    - name: redhat
      image: docker.io/rkalluru/learnk8s:rhel9-bare