apiVersion: v1
kind: Pod
metadata:
  name: service-demo
  labels:
    topic: services
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        containerPort: 80

---
# cluster ip
apiVersion: v1
kind: Service
metadata:
  name: service-cluster-ip
spec:
  selector:
    topic: services
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

---

apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
    - name: redhat
      image: rkalluru/learnk8s:rhel9-bare


# kubectl apply -f 17*
# kubectl exec get svc

# kubectl exec -it debug -- bash

# curl {ip of cluster ip} ip may get changed

# so give
# curl service-cluster-ip  # direct pod

# delete the cluster ip and again exec the services

# again give curl cluster ip

# it will not work because ip got changed

# go with pod name directly

# kubectl get svc service-cluster-ip -o yaml

# kubectl get endpoints

# kubectl get pods -o wide

---
# node port
apiVersion: v1
kind: Service
metadata:
  name: service-np
spec:
  type: NodePort
  selector:
    topic: services
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

# if one node is executing a service on a port
# then if another node comes into picture then this node also hits the same service on same port

---
# load balancer
apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: LoadBalancer
  selector:
    topic: services
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

---
# ExternalName
apiVersion: v1
kind: Service
metadata:
  name: service-external-name
spec:
  type: ExternalName
  ExternalName: { lb }














